### ISSUE TITLE
Add a button to copy code

### ISSUE THREAD

**Issue by BoyWithSilverWings** [BoyWithSilverWings/json-formatter#10]
Button needs to activate only when there is content in the main editor

**Comment by JGriffCS** [comment]
Also, do you know of a reactive way (one in which a rerender will trigger) to obtain the current content of the editor? I haven't been able to find a way to perform actions when the editor goes from being empty to not and vice versa from within the Sidebar component. The content can be retrieved from the `editorConfig` object passed as a prop into the sidebar, but since the contents are returned from it's `getValue` method the sidebar doesn't know to rerender when that value changes as it can't watch that function.

**Comment by BoyWithSilverWings** [comment]
@JGriffCS There are two operations that I see could be beneficial for someone using the mouse. 
1. Copy
2. Clear

Currently we do not have the controlled Monaco editor, so showing them only when there is content in the edtiro is unfortunately no an option. But we do have to plan for it. 

I was thinking on the lines of a floating action buton. Something like [React Tiny Fab](https://dericgw.github.io/react-tiny-fab/) could work the trick. 

Do comment if you can think of something that might not work because of this or if you have something better in mind.

**Comment by JGriffCS** [comment]
Thanks for the additional info! The React Tiny Fab library looks pretty straight forward and looks like it would mesh well with the editor. To confirm, your thought is to place an "actions bar" floating at the bottom of the editor that would, for now, contain a button to copy the entire contents to the editor and another button to clear the entire contents from the editor? Something like this?:

![Copy to Clipboard v2](https://user-images.githubusercontent.com/7431677/67141041-d1304e00-f29a-11e9-88c8-9540e2819f2a.PNG)

**Comment by BoyWithSilverWings** [comment]
We don't need a bar per se. We just need a button, that would show the copy and clear buttons on hover. 

Something like the React FAB demo: 

![image](https://user-images.githubusercontent.com/8883368/67141679-a84e8f80-f27f-11e9-8882-a4955f0622a3.png)

**Comment by JGriffCS** [comment]
Ahhhh, sorry, I totally misunderstood what React Fab was doing and instead was looking at the tools associated with the code example on the page itself haha 🤦‍♂ I see what React Fab is doing now. I think that should be pretty straight forward. 

Do you have any preferences on styling? I could leverage the `Action` components from the example and use the `copy` and `close` svgs for the copy/clear actions, or, if you'd prefer a different style, look into creating custom button actions.

**Comment by BoyWithSilverWings** [comment]
@JGriffCS  Don't have any preferences as of now, feel free to go ahead
