### ISSUE TITLE
Add button to collapse or expand all objects, arrays in main editor

### ISSUE THREAD

**Issue by BoyWithSilverWings** [BoyWithSilverWings/json-formatter#11]
This can be added to the floating FAB button that is now used for copy and clear. 

References:
https://stackoverflow.com/questions/50148938/fold-unfold-on-click-of-button-in-monaco-editor

**Comment by howareyouami** [comment]
@BoyWithSilverWings  Please assign this to me.

**Comment by BoyWithSilverWings** [comment]
@howareyouami  All yours. :smile:

**Comment by BoyWithSilverWings** [comment]
Fixed by #40
