### ISSUE TITLE
Write up a manifest file for a PWA

### ISSUE THREAD

**Issue by BoyWithSilverWings** [BoyWithSilverWings/json-formatter#17]
References:
1. https://developers.google.com/web/fundamentals/web-app-manifest/
2. https://developer.mozilla.org/en-US/docs/Web/Manifest

See if something like an [Asset Generator](https://github.com/onderceylan/pwa-asset-generator) would come in handy.

**Comment by arturparkhisenko** [comment]
@BoyWithSilverWings can I take this one? Hacktoberfest!

**Comment by BoyWithSilverWings** [comment]
@arturparkhisenko  sure, it's all yours
