### ISSUE TITLE
Transformation tab heading is not visible on dark theme

### ISSUE THREAD

**Issue by BoyWithSilverWings** [BoyWithSilverWings/json-formatter#18]
Current:
![screenshot](https://user-images.githubusercontent.com/8883368/64076631-c4ed3300-cce4-11e9-8b5a-72488dfd5ae8.png)

Expected:
The heading and button should be on a white background and visible.

**Comment by brendan-c** [comment]
I'll work on this issue :)

**Comment by brendan-c** [comment]
I've made the changes and submitted PR https://github.com/BoyWithSilverWings/json-formatter/pull/22
