### ISSUE TITLE
Editor does not resize with the browser

### ISSUE THREAD

**Issue by BoyWithSilverWings** [BoyWithSilverWings/json-formatter#7]
Leaves a background when resized

**Comment by saravanan10393** [comment]
I will take this issue.

**Comment by BoyWithSilverWings** [comment]
@saravanan10393 Sure. Let me know if you have any queries.

**Comment by BoyWithSilverWings** [comment]
@saravanan10393  Are you still working on this?

**Comment by JGriffCS** [comment]
@BoyWithSilverWings 

I think I found a very quick solution for this. Is it alright if I take over and open a PR?

**Comment by BoyWithSilverWings** [comment]
Since I had assigned this to @saravanan10393  earlier, I will wait a day for him to revert on this. Otherwise, I will take your PR. 
Anyways great work :smile:

**Comment by BoyWithSilverWings** [comment]
Fixed by #32
